config/routes.rb
Rails.application.routes.draw do
  #add root path
  root 'tutorials#index'
  #google auth handel
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  post 'user/signout', to: 'sessions#destroy', as: 'signout'
  get 'auth/failure', to: redirect('/')
  #link like handle
  post 'like/:id', to: 'tutorials#like', as: 'like'
  #for tutorials
  resources :tutorials, only: [:index, :show, :new, :create]
  #for request
  resources :requests, except: [:edit, :update, :show]

  #came from requests#index new link add form and save
  get 'tutorial_links/accept/:id', to: 'tutorial_links#accept', as: 'accept_tutorial_link'
  resources :tutorial_links, only: [:create, :new]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
	validates :category, :link, presence: true
	validates :link, format: { with: URI::regexp(%w(http https)),
    message: "not valid, Url must with http:// || https://" }
	belongs_to :user
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
	validates :category, presence: true 
	has_many :tutorial_links, dependent: :destroy

	def slug
		category.gsub(" ", "-")
	end

	def to_param
		"#{slug}"
	end
end

app/models/tutorial_link.rb
class TutorialLink < ActiveRecord::Base
	belongs_to :tutorial
	belongs_to :user
	acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :tutorial_links, dependent: :destroy
	has_many :requests

	validates :email, uniqueness: true

	def self.catch_user(auth)
		where(email: auth['info']['email']).first || keep_user(auth)
	end
	def self.keep_user(auth)
		user = User.new
		user.email = auth['info']['email']
		user.name = auth['info']['name']
		user.image = auth['info']['image']
		user.profile = auth['extra']['raw_info']['profile']
		user.save
		user
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  private
  def current_admin
    if session[:admin_id] == nil
      false
    else
      true
    end
  end
  helper_method :current_admin

  private
  def check_admin
    if session[:admin_id] == nil
      redirect_to root_path, notice: 'You don\'t have permission for this area' 
    end
  end

  private
  def require_login
  	if !current_user
  		redirect_to :back, notice: 'You need to be signed in'
  	end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :check_admin, except: [:new, :create]

  def index
    @data = Request.all
  end

  def new
  	@request = Request.new
  end

  def create
    @request = current_user.requests.build(request_params)
    if @request.save
      redirect_to root_path, notice: 'Tutorial Submitted'
    else
      render :new
    end
  end

  def destroy
    request = Request.find(params[:id])
    if request.destroy
      redirect_to :back, notice: 'Request Deleted'
    else
      redirect_to :back, notice: 'Something Wrong'
    end
  end

  private
  def request_params
    params.require(:request).permit(:category, :link, :user_id)
  end

  private
  def tutorial_link_params
    params.require(:tutorial_link).permit(:title, :link, :user_id, :tutorial_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.catch_user(env["omniauth.auth"])
		session['user_id'] = user.id
		if Admin.exists?(user_id: user.id)
			session['admin_id'] = true
		end
		redirect_to :back, notice: 'You are now signed in'
	end

	def destroy
		session['user_id'] = nil
		session['admin_id'] = nil
		redirect_to root_path, notice: 'Good Bye '
	end
end

app/controllers/tutorial_links_controller.rb
class TutorialLinksController < ApplicationController
	before_action :check_admin
	def new
	    @tutorialLink = TutorialLink.new
  	end

	def accept
	    @request = Request.find(params[:id])
	    @tutorialLink = TutorialLink.new
  	end

  	def create
  		if params[:tutorial_link][:request]
  			@request = Request.find(params[:tutorial_link][:request])
	    	@tutorialLink = TutorialLink.new(tutorial_link_accept_params)
	    	if User.exists?(@tutorialLink.user_id)
	      		if @tutorialLink.save
	        		@request.destroy
	        		redirect_to requests_path, notice: 'New Tutorial Created'
	      		else
	      			render :accept
	      		end
	    	else
	    		#Here is a problem, this flash message show two times, leter i need to solve this
	    		flash[:notice] = 'User id is not valid'
	      		render :accept
	    	end
	    else
	    	@tutorialLink = current_user.tutorial_links.build(tutorial_link_new_params)
	    	if @tutorialLink.save
	        	redirect_to new_tutorial_link_path, notice: 'New Tutorial Created'
	      	else
	      		render :new
	      	end
  		end
  	end

	private
	def tutorial_link_accept_params
		params.require(:tutorial_link).permit(:title, :link, :user_id, :tutorial_id)
	end
	private
	def tutorial_link_new_params
		params.require(:tutorial_link).permit(:title, :link, :tutorial_id)
	end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
	before_action :require_login, except: [:index, :show]
	before_action :check_admin, only: [:new, :create]

	def new
		@tutorial = Tutorial.new
		@data = Tutorial.all
	end

	def create
		@tutorial = Tutorial.new(tutorial_params)
		@data = Tutorial.all
		if @tutorial.save
			redirect_to :back, notice: 'Category Added'
		else
			render :new
		end
	end

	def index
		@data = Tutorial.all.order(category: :asc)
	end

	def show
		@category = params[:id].gsub("-", " ")
		@tutorial = Tutorial.where(category: @category).take
		@data = TutorialLink.where(tutorial_id: @tutorial.id)
	end

	def like
		@link = TutorialLink.find(params[:id])
		@link.liked_by current_user
		redirect_to :back
	end

	private
	def tutorial_params
		params.require(:tutorial).permit(:category)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/tutorial_links_helper.rb
module TutorialLinksHelper
	def getImage(tutorial_link)
		@user = User.find(tutorial_link.user_id)
		@user
	end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
	def tablePintingLogic(data_amount)
		amount = Array.new
		extra = data_amount % 3
		data_amount -= extra
		data_amount /= 3
		if extra == 2
			amount.push(data_amount + 1)
			amount.push(data_amount + 1)
			amount.push(data_amount)
		elsif extra == 1
			amount.push(data_amount + 1)
			amount.push(data_amount)
			amount.push(data_amount)
		else
			amount.push(data_amount)
			amount.push(data_amount)
			amount.push(data_amount)
		end

		return amount
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expand</title>
  <%= stylesheet_link_tag    'application', 'theme', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= msg %>
  </div>
<% end %>

<div id="status">
<div id="update">
<div class="container">

<header>
  <div class="pull-right">
    <% if current_admin %>
      <%= link_to 'Add Category', new_tutorial_path %>&nbsp;&nbsp;
      <%= link_to 'Add Tutorial', new_tutorial_link_path %>&nbsp;&nbsp;
      <%= link_to 'Requests', requests_path %>&nbsp;&nbsp;
      <% %>
    <% end %>  
    <% if not current_user %>
    <a href="" data-toggle="modal" data-target="#myModal">
      <i class="fa fa-plus"></i>
      Submit a Tutorial
    </a>
    <% else %>
    <%= link_to new_request_path do %>
    <i class="fa fa-plus"></i>
      Submit a Tutorial
    <% end %>
    <% end %>
    &nbsp;&nbsp;
    <% if current_user %>
      <%= link_to(signout_path, method: :post) do %>
        <i class="fa fa-sign-out"></i>
        Signout
      <% end %>
    <% else %>
      <a href="" data-toggle="modal" data-target="#myModal">
        <i class="fa fa-sign-in"></i>
        Signup/Signin
      </a>
    <% end %>
  </div>
</header>

<p>&nbsp;</p>

<div class="row header">
  <%= link_to root_url do %>
    <h3>Expand</h3>
  <% end %>
  <p>Share and discover the best programming tutorials and courses online.</p>
</div>

<%= yield %>

<div class="row">
  <div class="col-md-6">    
    <div class="pull-left github-color">
      <!-- <a href="#">About Us</a> 
      |-->
      <a href="mailto:minuddinrana@gmail.com">E-Mail Us</a>
    </div>
  </div>
  <div class="col-md-6">
    <div class="pull-right">
      <%= link_to image_tag('fb-icon.png'), "https://www.facebook.com/minuddin.ahmed.rana", target: 'blank' %>
      <%= link_to image_tag('social-tw.png'), "https://twitter.com/Minuddin_Ahmed", target: 'blank' %>
    </div>
  </div>
</div>

</div>
</div>
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->  
<!-- end olark code -->
</div>

<% if not current_user %>
<%= render "login" %>
<% end %>

</body>
</html>

app/views/requests/index.html.erb
<h2>User Requests</h2>

<% @data.each do |e| %>
<div class="row highlight">
	<div class="col-md-10">
		<h4>User Id: <%= e.user_id %></h4>
		<b><p>Category: <%= e.category %></p></b>
		<p>Link: <%= link_to e.link, e.link %></p>
	</div>
	<div class="col-md-2">
		<%= button_to 'ADD', accept_tutorial_link_path(e), method: 'get', class: 'btn btn-success' %><p>&nbsp;</p>
		<%= button_to 'DELETE', e, method: :delete, class: 'btn btn-danger' %>
	</div>
</div>
<% end %>

app/views/requests/new.html.erb
<%= simple_form_for @request do |f| %>
  <div class="modal-header">
    <h4 id="myModalLabel" class="modal-title">Submit a Tutorial</h4>
  </div>
  <div class="modal-body">
    Did you find an awesome course or tutorial? Submit the link below. We'll email you once it is live on the site.<p>&nbsp;</p>
    <div class="fields">
      <%= f.error_notification %>
      <%= f.input :category %>
      <%= f.input :link %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Submit Request' %>
  </div>
<% end %>

app/views/tutorial_links/_tutorial_link.html.erb
<%= div_for(tutorial_link) do %>
<% @user = getImage(tutorial_link) %>
    <div class="date">
        <div class="avatar">
            <%= link_to(@user.profile) do %>
                <%= image_tag(@user.image, title: @user.name) %>
            <% end %>
        </div>      
        <div class="vote-widget">
            <%= link_to "", like_path(tutorial_link), method: :post, class: 'upvote' %>
            <span class="vote-count"><%= tutorial_link.get_likes.size %></span>
        </div>
        <div class="wrapper">
            <div class="day">
                <%= link_to tutorial_link.title, tutorial_link.link, class: 'js-tutorial', title: tutorial_link.title, target: target="_blank" %>&nbsp;
            </div>
            <p class="ok"><%= tutorial_link.link %></p>
        </div>
    </div>
<% end %>

app/views/tutorial_links/accept.html.erb
<h1>Accept Request</h1>
<div class="highlight">
	<h4>User Id: <%= @request.user_id %></h4>
	<b><p>Category: <%= @request.category %></p></b>
	<p>Link: <%= link_to @request.link, @request.link %></p>
</div>

<%= simple_form_for @tutorialLink do |f| %>
<%= f.error_notification %>
<%= f.input :request, label: false, input_html: { value: @request.id, type: 'hidden' } %>
<%= f.input :user_id, input_html: { value: @request.user_id } %>
<%= f.association :tutorial, label_method: :category, value_method: :id, include_blank: false, label: 'Category' %>
<%= f.input :title %>
<%= f.input :link %>
<%= f.button :submit, 'Add Tutorial' %>
<% end %>

app/views/tutorial_links/new.html.erb
<h1>Add Tutorial Link</h1>
<%= simple_form_for @tutorialLink do |f| %>
<%= f.error_notification %>
<%= f.association :tutorial, label_method: :category, value_method: :id, include_blank: false, label: 'Category' %>
<%= f.input :title %>
<%= f.input :link %>
<%= f.button :submit, 'Add Tutorial' %>
<% end %>

app/views/tutorials/_login.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form role="form" action="<%= root_url %>auth/google_oauth2" method="get">
        <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 id="myModalLabel" class="modal-title">
            Login through your Google account.
          </h4>
        </div>

        <div class="modal-body">
          Login to Expand via your Google or Google Apps for Business account.
        </div>
        
        <div class="modal-footer">
          <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
          <button class="btn" type="submit" style="background-color:#3079ed;color:#fff;">Login via Google</button>
        </div>
      </form>
  </div>
</div>

app/views/tutorials/index.html.erb
<% data_amount = tablePintingLogic @data.count %>    
    <div class="row">

      <div class="col-md-4">
      <div class="panel panel-default modules">
          <table class="table table-hover">
            <tbody>
            <% for i in 0..data_amount[0]-1 %>
              <tr>
                <td class="pading-0">
                  <%= link_to @data[i].category, @data[i], class: "clickable-row" %>  
                </td>
              </tr>
            <% end -%>
            </tbody>
          </table>
      </div>
      </div>

      <div class="col-md-4">
      <div class="panel panel-default modules">
        <table class="table table-hover">
          <tbody>            
            <% for i in i+1..data_amount[0]+data_amount[1]-1 %>
              <tr>
                <td class="pading-0">
                  <%= link_to @data[i].category, @data[i], class: "clickable-row" %>   
                </td>
              </tr>
            <% end -%>
          </tbody>
        </table>          
      </div>
      </div>

      <div class="col-md-4">
      <div class="panel panel-default modules">
        <table class="table table-hover">
          <tbody>            
            <% for i in i+1..data_amount[0]+data_amount[1]+data_amount[2]-1 %>
              <tr>
                <td class="pading-0">
                  <%= link_to @data[i].category, @data[i], class: "clickable-row" %>   
                </td>
              </tr>
            <% end -%>
          </tbody>
        </table> 
      </div>
      </div>

    </div>

    <p>&nbsp;</p>

app/views/tutorials/new.html.erb
<h1>Add New Category</h1>
<%= simple_form_for @tutorial do |f| %>
<%= f.error_notification %>
<%= f.input :category %>
<%= f.button :submit, 'Add Category' %>
<% end %>
<p>&nbsp;</p>
<% data_amount = tablePintingLogic @data.count %>    
    <div class="row">

      <div class="col-md-4">
      <div class="panel panel-default modules">
          <table class="table table-hover">
            <tbody>
            <% for i in 0..data_amount[0]-1 %>
              <tr>
                <td class="pading-0">
                  <%= link_to @data[i].category, @data[i], class: "clickable-row" %>  
                </td>
              </tr>
            <% end -%>
            </tbody>
          </table>
      </div>
      </div>

      <div class="col-md-4">
      <div class="panel panel-default modules">
        <table class="table table-hover">
          <tbody>            
            <% for i in i+1..data_amount[0]+data_amount[1]-1 %>
              <tr>
                <td class="pading-0">
                  <%= link_to @data[i].category, @data[i], class: "clickable-row" %>   
                </td>
              </tr>
            <% end -%>
          </tbody>
        </table>          
      </div>
      </div>

      <div class="col-md-4">
      <div class="panel panel-default modules">
        <table class="table table-hover">
          <tbody>            
            <% for i in i+1..data_amount[0]+data_amount[1]+data_amount[2]-1 %>
              <tr>
                <td class="pading-0">
                  <%= link_to @data[i].category, @data[i], class: "clickable-row" %>   
                </td>
              </tr>
            <% end -%>
          </tbody>
        </table> 
      </div>
      </div>

    </div>

    <p>&nbsp;</p>

app/views/tutorials/show.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="messages">
          <h1 style="font-size:22px;margin-bottom: 25px;">
            	<%= @category %> Tutorials and Courses
        	</h1>&nbsp;
			<p>&nbsp;</p>
            <% if @data %>
    			<div id="tutorial_links">
    				<%= render :partial => @data %>
    			</div>
            <% else %>
                <div class="highlight">
                    <h3>NO Tutorials or Courses are available</h3>
                </div>
            <% end %>
		</div><p>&nbsp;</p>
    </div>
</div>